ARG MY_IMAGE=ocp_image

FROM $MY_IMAGE

ARG PATCH_LIST=patch-list.txt
ARG REPO_LIST=ubi9.repo
ENV PATCH_FILE="${PATCH_LIST}"
ENV REPO_FILE="${REPO_LIST}"

COPY "${PATCH_FILE}" "${REPO_FILE}" /tmp/
COPY patch-image.sh /bin/

RUN echo "patch list file: ${PATCH_FILE}" \
 && if [ ! "$(ls -A /etc/yum.repos.d/)" ]; then cp /tmp/${REPO_FILE} /etc/yum.repos.d/; fi \
 && dnf install -y git python3 python3-pip wget unzip patch \
 && /bin/patch-image.sh \
 && rm -f /bin/patch-image.sh \
 && dnf clean all \
 && rm -rf /var/cache/{yum,dnf}/*
